publishDir = "docs"
baseURL       = "https://aandrin25.github.io/github.io/"
languageCode  = "en-us"
title         = "Nadri Network | Personal Portfolio"
theme         = "roxo"
summarylength = 25

# Site Menus
[menu]
  # Navbar Menus
  [[menu.nav]]
    name    = "Home"
    url     = ""
    weight  = 1
  [[menu.nav]]
    name    = "About Me"
    url     = "about"
    weight  = 2
  [[menu.nav]]
    name    = "Professional Ventures"
    url     = "portfolio"
    weight  = 3
  [[menu.nav]]
    name    = "Data Science Projects"
    url     = "blog"
    weight  = 4
  [[menu.nav]]
    name    = "Get in touch"
    url     = "contact"
    weight  = 5

# Site Params
[params]
  enable = true
  logo = "images/logo.png"
  dateFormat = "26 FEB 1994"
  # Meta data
  description = "Roxo Hugo themes | Design Agency Template by StaticMania"
  author = "StaticMania"
  # Google Analitycs
  googleAnalitycsID = "G-1EN4F0GPK4"
  # We're using formspree.io for form handling, paste your formspree url below
  formspreeFormUrl  = "https://formspree.io/f/xrgjwjbd"

  # Contact Form
  [params.contactForm]
    placeholder_first_name        = "First Name"
    placeholder_last_name         = "Last Name"
    placeholder_email             = "Email"
    placeholder_project_type      = "Inquiry Type"
    placeholder_about_the_project = "Tell me about your Needs"
    send_message                  = "Send Message"

    [[params.contactForm.projectType]]
      value = "gd"
      title  = "Kissable Keychains"
    [[params.contactForm.projectType]]
      value = "wd"
      title  = "Data Science"

  # Navbar Action Button
  [params.navAction]
    status  = true
    name    = "Get in touch"
    url     = "contact"


  # Banner Section
  [params.banner]
    enable                = true
    background_image      = "images/backgrounds/orange-and-black.png"
    heading               = "Averya Andrin. Mother. Business Owner. Data Scientist."
    tagline               = "Professional Portfolio"
    primary_button        = "Shop my store"
    primary_button_url    = "https://www.kissablekeychains.com/"
    secondary_button      = "Connect with Us"
    secondary_button_url  = "contact"

  [params.portfolio]
    enable    = true
    title     = "SHOP MY STORE"
    subtitle  = "Support my small business."

  [params.call_to_action]
    enable              = true
    background_image    = "images/backgrounds/cta-background.jpg"
    title               = "LET’S WORK TOGETHER"
    primary_button      = "Submit Query"
    primary_button_url  = "contact"
    secondary_button    = "Not Convinced"
    secondary_button_url = "portfolio"

  [params.footer]
    # Footer Contact Info
    [params.footer.contactInfo]
      title   = "Contact Info"
      address = "4314 Azalea Walk<br>Ellenwood, GA 30294"
      phone   = "470-495-1525"
      email   = "aandrin25@gmail.com"
      # Footer Sitemap
      [params.footer.sitemap]
        title   = "Sitemap"
        [[params.footer.sitemap.link]]
          name = "About Me"
          url  = "about"
        [[params.footer.sitemap.link]]
          name = "Data Science Projects"
          url  = "portfolio"
        [[params.footer.sitemap.link]]
          name = "Professional Ventures"
          url  = "blog"
        [[params.footer.sitemap.link]]
          name = "Contact"
          url  = "contact"
      # Footer Social Media
      [params.footer.social]
        title   = "Personal Social Media"
        [[params.footer.social.link]]
          name = "LinkedIn"
          url  = "https://www.linkedin.com/in/averya-andrin-747a495b/"
        [[params.footer.social.link]]
          name = "Facebook"
          url  = "https://www.facebook.com/averya.andrin/"
        [[params.footer.social.link]]
          name = "Twitter"
          url  = "https://twitter.com/averywithana"
        [[params.footer.social.link]]
          name = "GitHub"
          url  = "https://github.com/aandrin25/"
      # Footer Service
      [params.footer.service]
        title       = "Averya Andrin"
        description = "- Businness Owner<br>- Self Taught Data Scientist"
